OPENAI_API_KEY = "sk-p4LGv64tbvvRLl1gwIDnRYPmGlUrF7Ksa6f7TrYv0cEIOQwa"
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_SPECIFIC_ACCOUNT_ID = 0
OPENAI_API_URL = "https://api.chatanywhere.com.cn"
LINE_BOT_API = ""
LINE_CHANNEL_SECRET = ""
